name: Hardhat Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup NodeJS 20.12.2
              uses: actions/setup-node@v2
              with:
                node-version: 20.12.2
                cache: npm
            - name: Show NodeJS version 
              run: npm --version
            
            - name: Install Hardhat
              run: npm install --save-dev hardhat@2.22.3
            
            - name: Install Hardhat Dependencies
              run: npm ci

          
            - name: Run Slither
                  uses: crytic/slither-action@v0.4.0
                  id: slither
                  with:
                    node-version: 20.9.0
                    fail-on: high
                    slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/


